<a href="https://colab.research.google.com/github/ybeth-gonzaga/Taylor-Swift-Spotify-Analysis/blob/main/03_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import re
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
# Import File
df = pd.read_csv("https://raw.githubusercontent.com/ybeth-gonzaga/Taylor-Swift-Spotify-Analysis/main/ph_spotify_daily_charts_ts_summary.csv")
df.head()

,Unnamed: 0,date,total_streams,stream_percent_change,total_count,count_percent_change,highest_rank,top_rank_diff
0,0,2017-01-01,0,0.0,0,0.0,NaN,0.0
1,1,2017-01-02,0,0.0,0,0.0,NaN,0.0
2,2,2017-01-03,0,0.0,0,0.0,NaN,0.0
3,3,2017-01-04,0,0.0,0,0.0,NaN,0.0
4,4,2017-01-05,0,0.0,0,0.0,NaN,0.0

# Count Analysis

In [9]:
# Sort the 30 highest number of charting songs by date
df_count_ranked.sort_values(by='total_count', ascending=False).head(30).sort_values(by='date')

,Unnamed: 0,date,total_streams,stream_percent_change,total_count,count_percent_change,highest_rank,top_rank_diff
1772,1772,2021-11-12,8476377,1053.848259,47,213.333333,1.0,-32.0
1773,1773,2021-11-13,6443379,-23.984280,45,-4.255319,1.0,0.0
1774,1774,2021-11-14,5136173,-20.287585,45,0.000000,1.0,0.0
1775,1775,2021-11-15,5125739,-0.203147,44,-2.222222,1.0,0.0
1776,1776,2021-11-16,4448454,-13.213412,44,0.000000,1.0,0.0
1777,1777,2021-11-17,4002500,-10.024921,42,-4.545455,1.0,0.0
1778,1778,2021-11-18,3787237,-5.378214,43,2.380952,1.0,0.0
1779,1779,2021-11-19,3287671,-13.190777,42,-2.325581,1.0,0.0
1780,1780,2021-11-20,2654654,-19.254268,38,-9.523810,1.0,0.0
2378,2378,2023-07-07,20159438,294.685730,56,55.555556,1.0,0.0
2379,2379,2023-07-08,14318720,-28.972623,52,-7.142857,1.0,0.0
2380,2380,2023-07-09,12270440,-14.304910,53,1.923077,1.0,0.0
2381,2381,2023-07-10,11663197,-4.948828,53,0.000000,1.0,0.0
2382,2382,2023-07-11,10215304,-12.414203,52,-1.886792,1.0,0.0
2383,2383,2023-07-12,9220814,-9.735295,51,-1.923077,1.0,0.0
2384,2384,2023-07-13,8397963,-8.923843,50,-1.960784,2.0,1.0
2385,2385,2023-07-14,7868552,-6.304041,49,-2.000000,4.0,2.0
2386,2386,2023-07-15,7237005,-8.026216,49,0.000000,4.0,0.0
2387,2387,2023-07-16,6843507,-5.437305,48,-2.040816,4.0,0.0
2388,2388,2023-07-17,7166971,4.726582,48,0.000000,4.0,0.0
2389,2389,2023-07-18,6788104,-5.286292,46,-4.166667,4.0,0.0
2390,2390,2023-07-19,6510918,-4.083408,46,0.000000,4.0,0.0
2391,2391,2023-07-20,6275801,-3.611119,44,-4.347826,4.0,0.0
2392,2392,2023-07-21,6037440,-3.798097,42,-4.545455,4.0,0.0
2393,2393,2023-07-22,5454899,-9.648808,40,-4.761905,4.0,0.0
2394,2394,2023-07-23,5083173,-6.814535,38,-5.000000,4.0,0.0
2395,2395,2023-07-24,5302578,4.316300,38,0.000000,4.0,0.0
2396,2396,2023-07-25,5106956,-3.689187,38,0.000000,4.0,0.0
2403,2403,2023-08-01,5510443,7.563340,39,5.405405,3.0,-1.0
2412,2412,2023-08-10,5066932,13.589469,39,14.705882,3.0,0.0

# Percent Change in Streams Analysis

In [8]:
df.sort_values(by='stream_percent_change', ascending=False)

,Unnamed: 0,date,total_streams,stream_percent_change,total_count,count_percent_change,highest_rank,top_rank_diff
178,178,2017-07-01,16862,inf,1,inf,200.0,0.0
715,715,2018-12-20,22088,inf,1,inf,194.0,0.0
842,842,2019-04-26,433059,inf,4,inf,1.0,0.0
722,722,2018-12-27,21206,inf,1,inf,193.0,0.0
708,708,2018-12-13,23801,inf,1,inf,175.0,0.0
...,...,...,...,...,...,...,...,...
424,424,2018-03-04,0,-100.0,0,-100.0,NaN,0.0
749,749,2019-01-23,0,-100.0,0,-100.0,NaN,0.0
710,710,2018-12-15,0,-100.0,0,-100.0,NaN,0.0
745,745,2019-01-19,0,-100.0,0,-100.0,NaN,0.0
541,541,2018-06-29,0,-100.0,0,-100.0,NaN,0.0

In [ ]:
# There exists inf values due to limitations that only top 200 songs have the recorded stream
# To fix that, exchange inf to NaN

In [19]:
# Replace 'inf' values with NaN
df['stream_percent_change'] = df['stream_percent_change'].replace(np.inf, np.nan)

# Convert the column to numeric data type
df['stream_percent_change'] = pd.to_numeric(df['stream_percent_change'])

# check if inf is gone
df['stream_percent_change'].value_counts()

stream_percent_change
 0.000000      493
-100.000000     10
 1.150611        1
-0.483002        1
-4.299148        1
              ...
 7.659308        1
-1.158338        1
-11.221965       1
-3.137291        1
 5.683393        1
Name: count, Length: 1967, dtype: int64

In [21]:
streams_df = df.sort_values(by='stream_percent_change', ascending=False)
streams_df.head(30)

,Unnamed: 0,date,total_streams,stream_percent_change,total_count,count_percent_change,highest_rank,top_rank_diff
1297,1297,2020-07-24,5019956,3173.848763,25,400.000000,1.0,-114.0
1437,1437,2020-12-11,2989691,1425.158016,22,340.000000,1.0,-83.0
1772,1772,2021-11-12,8476377,1053.848259,47,213.333333,1.0,-32.0
2119,2119,2022-10-21,12926945,955.448643,36,125.000000,1.0,-39.0
1556,1556,2021-04-09,4476141,924.487829,30,328.571429,1.0,-3.0
2084,2084,2022-09-16,971098,836.196591,14,366.666667,53.0,-58.0
961,961,2019-08-23,2188177,501.192121,18,350.000000,1.0,-5.0
1500,1500,2021-02-12,880686,482.660818,10,150.000000,1.0,-73.0
1716,1716,2021-09-17,324344,315.484730,4,100.000000,6.0,-112.0
2378,2378,2023-07-07,20159438,294.685730,56,55.555556,1.0,0.0
1627,1627,2021-06-19,327582,234.584861,10,233.333333,51.0,-72.0
1436,1436,2020-12-10,196025,214.651921,5,150.000000,84.0,-71.0
1699,1699,2021-08-31,98308,201.873119,3,200.000000,134.0,-17.0
331,331,2017-12-01,246707,190.383597,9,200.000000,71.0,-22.0
891,891,2019-06-14,392059,168.664213,5,400.000000,5.0,-3.0
1947,1947,2022-05-06,1082567,155.661277,11,57.142857,2.0,-44.0
1421,1421,2020-11-25,144900,122.895644,4,100.000000,99.0,-43.0
1419,1419,2020-11-23,58735,119.676852,2,100.000000,170.0,-12.0
1531,1531,2021-03-15,260848,113.241774,7,75.000000,73.0,-10.0
1412,1412,2020-11-16,55831,113.079154,2,100.000000,158.0,-6.0
1405,1405,2020-11-09,57976,111.660764,2,100.000000,159.0,-3.0
954,954,2019-08-16,373147,105.400511,5,66.666667,11.0,-28.0
1669,1669,2021-08-01,111397,104.691118,3,50.000000,51.0,-106.0
931,931,2019-07-24,436754,104.344653,6,200.000000,16.0,-7.0
1542,1542,2021-03-26,313052,102.982636,5,25.000000,7.0,-73.0
1499,1499,2021-02-11,151149,92.374952,4,100.000000,74.0,-4.0
1496,1496,2021-02-08,135345,91.932442,4,100.000000,68.0,-5.0
1482,1482,2021-01-25,139543,90.133802,3,200.000000,33.0,0.0
1244,1244,2020-06-01,139997,75.228428,5,66.666667,114.0,-5.0
1554,1554,2021-04-07,311722,74.832023,6,20.000000,9.0,-70.0

In [22]:
df.to_csv('streams_analysis.csv', index=False)